plugins {
    id 'com.android.application'
}

android {
    namespace 'com.embabi.auctionflex'
    compileSdk 35

    defaultConfig {
        applicationId "com.embabi.auctionflex"
        minSdk 30
        targetSdk 35
        versionCode 430
        versionName "43.0-postgame-2s-delay"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
