plugins {
    id 'com.android.application'
}

android {
    namespace 'com.embabi.auctionbot'
    compileSdk 35

    defaultConfig {
        applicationId "com.embabi.auctionbot"
        minSdk 30
        targetSdk 35
        versionCode 30
        versionName "3.0-hidden-player-style"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}